extends Node
## Background music (assets/audio/music, generated by
## assets/audio/source/build_music.py). Autoloaded as "Music". Each scene asks
## for its track in _ready(); asking for the track that's already playing does
## nothing, so walking between rooms of one area doesn't restart the song.
## Tracks loop via the loop points baked into each WAV (intro plays once).

const TRACK_DIR := "res://assets/audio/music/"
const VOLUME_DB := -4.0

var _player: AudioStreamPlayer
var _current: String = ""
var _fade: Tween


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_player = AudioStreamPlayer.new()
	_player.volume_db = VOLUME_DB
	add_child(_player)


## Plays `track`, or `fallback` if that track hasn't been made yet (e.g. boss
## fights use the battle theme until a boss theme exists). A place with no
## music at all goes quiet rather than carrying the previous scene's song.
func play(track: String, fallback: String = "") -> void:
	var name_to_play := track
	if not ResourceLoader.exists(TRACK_DIR + track + ".wav"):
		name_to_play = fallback
	if name_to_play == "" or not ResourceLoader.exists(TRACK_DIR + name_to_play + ".wav"):
		stop()
		return
	if name_to_play == _current and _player.playing:
		return
	_kill_fade()
	_current = name_to_play
	_player.stream = load(TRACK_DIR + name_to_play + ".wav")
	_player.volume_db = VOLUME_DB
	_player.play()


## Stops the music, optionally fading out over `fade` seconds (used when the
## victory fanfare takes over at the end of a battle).
func stop(fade: float = 0.0) -> void:
	_current = ""
	_kill_fade()
	if fade <= 0.0 or not _player.playing:
		_player.stop()
		return
	_fade = create_tween()
	_fade.tween_property(_player, "volume_db", -40.0, fade)
	_fade.tween_callback(_player.stop)


func current() -> String:
	return _current


func _kill_fade() -> void:
	if _fade != null and _fade.is_valid():
		_fade.kill()
	_fade = null
