extends Node
## Plays the chiptune sound effects in assets/audio/sfx (generated by
## assets/audio/source/build_sfx.py). Autoloaded as "Sfx", so any script can
## call Sfx.play("menu_confirm") without owning an AudioStreamPlayer.

const SOUND_DIR := "res://assets/audio/sfx/"
const SOUNDS := [
	"attack", "spell", "hit",
	"menu_move", "menu_confirm", "menu_cancel",
	"victory", "level_up", "item", "equip",
	"encounter",
	"fire", "ice", "thunder", "earth", "holy", "heal", "poison",
]
# Enough voices that a hit landing during a spell doesn't cut the spell off.
const VOICES := 6

var _streams: Dictionary = {}
var _players: Array[AudioStreamPlayer] = []
var _next: int = 0


func _ready() -> void:
	# Keeps playing through scene changes (victory fanfare -> back to the map).
	process_mode = Node.PROCESS_MODE_ALWAYS
	for sound_name: String in SOUNDS:
		var path: String = SOUND_DIR + sound_name + ".wav"
		if ResourceLoader.exists(path):
			_streams[sound_name] = load(path)
	for i in VOICES:
		var p := AudioStreamPlayer.new()
		add_child(p)
		_players.append(p)


func play(sound_name: String) -> void:
	var stream: AudioStream = _streams.get(sound_name)
	if stream == null:
		push_warning("Sfx: no sound named '%s'" % sound_name)
		return
	# Round-robin over the voices; the oldest sound gets replaced if all are busy.
	var p: AudioStreamPlayer = _players[_next]
	_next = (_next + 1) % _players.size()
	p.stream = stream
	p.play()
